### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by nwesem** [janstieler/monkeyoffice-paypal-import#1]
hi jan, 

kannst du erklären wie der import mit der txt datei genau ausgeführt wird?

Vielen dank LG Niclas

**Comment by nwesem** [comment]
Habe es in der doku gefunden https://www.monkey-office.de/doc/Importdefinition_anlegen.html#28443458

-----

Found this website that explains how to import the paypal activity https://www.monkey-office.de/doc/Importdefinition_anlegen.html#28443458

**Comment by janstieler** [comment]
@nwesem sorry hab jetzt erst Deine Frage gelesen.
Aber es scheint ja das Du gefunden hast wie es funktioniert.
Den Link zur Prosaldo Hilfe hab ich der Readme hinzugefügt

Grüße
